### ISSUE TITLE
Handle voice messages/sound files correctly

### ISSUE THREAD

**Issue by x5f3759df** [hdghg/cjbot#20]
When trying to send record voice message through app:

`Cannot recognize action:  {"update_id":930875,"message":{"message_id":57600,"from":{"id":129653438,"first_name":"\u53cb\u9054","username":"%username%"},"chat":{"id":-1001043020159,"title":"s@","username":"%chatname%","type":"supergroup"},"date":1470163977,"voice":{"duration":3,"mime_type":"audio\/ogg","file_id":"AwADAgAD1AADvlq6B9cKig3ChCPtAg","file_size":6374}}}`

When trying to send sound files (mp3. ogg, etc - everything that uses builtin player):

`{"update_id":930882,"message":{"message_id":57617,"from":{"id":129653438,"first_name":"\u53cb\u9054","username":"%username%"},"chat":{"id":-1001043020159,"title":"s@","username":"%chatname%","type":"supergroup"},"date":1470164257,"audio":{"duration":2,"mime_type":"audio\/mpeg","file_id":"BQADAgAD1gADvlq6B4Cn_Kqw_BmEAg","file_size":17682}}}`

**Comment by hdghg** [comment]
https://github.com/hdghg/cjbot/commit/519f776c7a1af3a84d98d5fa5f5dabb295d462f1

**Comment by hdghg** [comment]
{"update_id":943774,"message":{"message_id":91172,"from":{"id":1488,"first_name":"Smokeweedeveryday"},"chat":{"id":1488,"title":"s@","username":"sniggers","type":"supergroup"},"date":1471256942,"video":{"duration":6,"width":640,"height":360,"thumb":{"file_id":"AAQCABO1WXENAASMMzKcAZsMgLIQAAIC","file_size":2196,"width":90,"height":50},"file_id":"BAADAgADBgAD_NoDDk7c-GXKOVEHAg","file_size":671297}}}

**Comment by hdghg** [comment]
Fixed in https://github.com/hdghg/goatway
