### ISSUE TITLE
Handle images and stickers correclty

### ISSUE THREAD

**Issue by hdghg** [hdghg/cjbot#7]

**Comment by x5f3759df** [comment]
Stickers can be send as unicode emojii they associated with.
Pictures, however, stored in telegram cloud, I think there is no way to resend them.

**Comment by hdghg** [comment]
Telegram bot api allows bots to obtain these images.
Images can be hosted then, and bot can send an url to uploaded image.
First solution: find any public image hosting without bot protection or
Second solution: convert application to web application, and keep small cache to host these images.
Third solution: send image as html content.
I like the second way, actually, but it adds some limitations, so I prefer to wait a little and look for for any better idea.

**Comment by hdghg** [comment]
Images now hosted and can be accessed by url
https://github.com/hdghg/cjbot/commit/a4b1c2050ad9801a82d8115c3e8a662af50f3085

**Comment by hdghg** [comment]
https://github.com/hdghg/cjbot/commit/e316f5f24ae30b0a270b8f283c5262c7361a4013
